"""RetailSense — 海外电商英文文案库（Etsy/Amazon Top Seller 风格）。"""

EN_PRODUCT_COPY = {
    "刻字狗牌": {
        "seo": "Personalized Engraved Dog Tag – 304 Stainless Steel, Double-Sided Laser Engraving, Rounded Mirror Polish\n• Solid 304 stainless steel – won't snap, rust, or wear through like cheap acrylic tags\n• Double-sided laser engraving that stays crisp for years – never fades, never rubs off\n• Rounded mirror-polished edges – smooth against your dog's coat, no sharp corners\n• 3 sizes × 5 colors to fit every collar, from Chihuahua to Great Dane\n• Deep engraving you can feel with your fingertip – your pet's name & your number, permanent\n★ Why ours: 35+ acrylic listings turn cloudy and unreadable in 3 months; ours is the same price but lasts the dog's whole life\ntags: engraved dog tag, personalized pet id tag, stainless steel dog tag, custom dog name tag, double sided engraving, indestructible dog tag, laser engraved pet tag",
        "social": "I've replaced my dog's ID tag FOUR times this year. The cute acrylic ones from the pet store start out adorable, but three months later the name is scratched off and the whole thing is cloudy. If Milo ever got loose, the tag would be useless. So I switched to a solid stainless steel one with double-sided laser engraving – I can literally feel the letters when I run my thumb over them. It's been six months of daily hikes, swimming, and wrestling with his sister, and the tag still looks brand new. His name, my phone number, permanent. That's the kind of 'I'll never worry again' purchase I wish I'd made years ago. 🐾",
        "sales": "🔥 4,200+ dogs wear this tag every day – and 1,800+ parents reorder for their second pet\n\n⏳ Last batch of the mirror-polish steel sold out in 6 days – only 120 units left this month\n\n💎 Pet stores charge $25–$35 for a stainless tag that only engraves ONE side. Ours is double-sided, laser-deep, and just $12.99\n\n✅ 30-day love-it guarantee – if it fades or scratches, we replace it free\n\n👉 Tap 'Add to Cart' now and engrave your best friend's name in under 2 minutes",
    },
    "发光项圈": {
        "seo": "Rechargeable LED Dog Collar – USB Magnetic Charging, IPX5 Waterproof, 3 Brightness Modes, 12H Battery\n• USB magnetic charge – plug it in like a phone; never buy another button battery again\n• IPX5 waterproof – rain, puddles, and splashes won't kill it, night after night\n• 3 brightness modes – steady, slow flash, and strobe for high-traffic visibility\n• 12-hour battery on a single charge – runs all week on evening walks\n• Fully adjustable 30–65 cm – one collar fits puppies to large breeds\n★ Why ours: 28 competing collars chew through batteries weekly ($$ every month); ours recharges in 2 hours for free\ntags: rechargeable led dog collar, usb dog collar light, waterproof light up collar, glow collar for dogs, night walk dog collar, flashing dog collar, reflective rechargeable collar",
        "social": "Winter walks were honestly scary before this. Our neighborhood has no streetlights, and I'd flinch every time a car turned the corner while Scout sniffed ahead of me in the dark. I tried the battery collars first – they'd die mid-walk after a week, and I was spending a small fortune on those little button batteries. This one just magnetically snaps onto a USB charger, lasts 12 hours, and I've walked through full-on downpours without it missing a beat. Now Scout glows like a little beacon and every driver sees him a block away. The strobe mode even got a thumbs-up from a dog-trainer friend. I don't walk him at night without it anymore. 🌙🐕",
        "sales": "🚨 Your dog is invisible to drivers after dark – 1 in 3 night-walk accidents happen because drivers can't see the dog\n\n⚡ Stop paying $8/week on button batteries – this collar recharges 500+ times for free\n\n🏆 6,800+ verified 5-star reviews. \"3 years, still going\" is our most common review line\n\n💰 Pet stores sell basic flashing collars for $40+. Ours: USB magnetic charge, waterproof, 3 modes – just $24.99\n\n⏳ Only 85 left in stock – grab yours before tonight's walk",
    },
    "珐琅名牌": {
        "seo": "Enamel Pet Nameplate – Copper Base, Hand-Painted Enamel, 800°C Fired, Vintage Royal Style, Gift Boxed\n• Solid copper base with hand-painted enamel color – a piece of jewelry, not a sticker\n• Fired at 800°C so the color bonds to the metal – never chips, never fades\n• Vintage royal-inspired design with gold-toned detailing – turns any collar into heirloom style\n• Arrives in a keepsake gift box – ready to give, no wrapping needed\n• Hand-finished by artisans, each one slightly unique – like a tiny portrait of your pet\n★ Why ours: 18 competitors silk-screen printed plates that fade in 6 months; ours is fired enamel that outlives the collar itself\ntags: enamel pet nameplate, personalized pet name plate, copper enamel dog tag, vintage pet tag, hand painted pet tag, luxury dog tag gift, keepsake pet id tag",
        "social": "When we said goodbye to our old boy, I wanted something more than the plastic tag he'd worn for years – something that felt like him. I found this enamel nameplate with hand-painted color and gold detailing, and when it arrived in its little gift box, I actually cried. It's fired in a kiln, not printed, so his name and the colors are set into the metal forever. It hangs in my kitchen now where I see it every morning, and the enamel hasn't dulled a single bit in over a year. It's not a tag – it's a little portrait of him. I've since bought them for every pet-parent friend, and each one says it's the most beautiful thing their dog owns. 💛",
        "sales": "👑 This is the tag pet parents photograph – 3,900+ sold, 4.9 stars, 'bought it as a memorial' in nearly every review\n\n🔥 Kiln-fired enamel, not silk-screen – printed plates from big retailers fade in 6 months; ours is guaranteed for life\n\n💎 Comparable artisan enamel tags on Etsy run $35–$50. Yours, hand-fired and gift-boxed: just $16.99\n\n🎁 Free keepsake gift box included – the #1 gift for new-pet parents, memorials, and Gotcha Days\n\n⏳ Only 60 pieces left this month (each one is hand-fired, so we physically can't restock fast) – secure yours now",
    },
    "亚克力牌": {
        "seo": "Ultra-Light Custom Acrylic Pet ID Tag | 2g Cat & Small Dog Name Tag | Waterproof Double-Sided UV Printed | Paw, Bone, Heart & Zodiac Designs\n• Feather-light 2g design: 90% lighter than metal tags, so cats and tiny dogs forget it's even there.\n• Frosted transparent acrylic with a clean Instagram-style look that matches any collar, not a clunky metal slab.\n• Double-sided UV printing that's fully waterproof: names and phone numbers stay crisp through rain, puddles, and play.\n• Personalize it your way: paw print, bone, heart, or zodiac motifs, sized and shaped for small necks.\n• Built for cats and small breeds that hate heavy, jangling tags that weigh down their collar.\nUnlike metal tags that clank and scratch your pet's chin, ours is a whisper-light frosted tag that's silent, stylish, and gentle — the only tag your small pet won't fight.\nSearch tags: custom acrylic pet tag, cat ID tag lightweight, small dog name tag, waterproof pet tag, personalized cat tag, frosted acrylic dog tag, 2g pet tag, zodiac pet tag",
        "social": "My cat wears this like it's part of her collar. She's 7 pounds, and every metal tag I tried made her shake her head and scratch at it all day. This acrylic one is so light she forgot it existed by lunchtime. I got the frosted clear with a tiny paw print and her name in my handwriting, and honestly it looks like something from a boutique pet shop, not a $9 accessory. Two months in, been through rain and the water bowl dunk test, print hasn't faded a bit. If your cat or small dog hates tags, this is the one that finally sticks.",
        "sales": "Metal tags start around $12 and your cat still hates them — ours is $8.99 and they don't even notice it. Over 2,300 five-star reviews say the same thing: 'the first tag my cat didn't rip off.' The frosted paw print style is our #1 seller and it's been in and out of stock all month. Order today and we'll engrave it free this week only. Small pets deserve a tag that doesn't feel like a punishment. Grab yours before the next restock.",
    },
    "宠物手链": {
        "seo": "Handmade Boho Pet Bracelet with Natural Gemstone | Black Obsidian, Rose Quartz & Tiger Eye | Waterproof Wax Cord | Matching Human & Pet Couple Set\n• Hand-woven from imported wax cord, so it's soft, flexible, and comfortable for everyday wear on your pet's collar or as a charm.\n• Accented with natural semi-precious stones: black obsidian, rose quartz, and tiger's eye, each with its own meaning and texture.\n• Matching human-and-pet couple set available, so you and your dog or cat can wear the same bracelet in coordinated colors.\n• Waterproof and washable, holds its color and shape through baths, rain, and rough play.\n• Bohemian woven style that looks handmade and intentional, not like a mass-produced pet accessory.\nMost pet bracelets are cheap nylon with plastic beads. Ours is genuinely hand-knotted wax cord wrapped around real gemstones, and it comes in a matching set for you and your pet — a keepsake, not just an accessory.\nSearch tags: handmade pet bracelet, boho dog bracelet, gemstone pet bracelet, matching pet and owner bracelet, rose quartz pet charm, obsidian dog collar charm, waterproof pet bracelet, couple pet bracelet set",
        "social": "I bought the rose quartz one for my dog and the matching one for myself, and now we match on our morning walks. It's hand-woven wax cord, so it doesn't fray or get gross like the nylon ones did, and it's survived baths, rain, and a lot of rolling in dirt. The little stone beads catch the light and people stop us to ask where I got them. It's become a thing now — my dog and I show up in the same bracelet and honestly it makes the whole walk feel special. Ten dollars-ish and it's lasted longer than collars I've paid triple for.",
        "sales": "This is a $14.99 keepsake that reads like $40 in a boutique, and it comes as a matching set for you and your pet. Our rose quartz and tiger's eye combos sold out twice last month, and the latest batch is already half gone. Buyers keep leaving reviews about strangers stopping them on walks to ask where the bracelet's from. Free shipping on 2+ sets ends Sunday. Order yours now and you'll both be wearing it before next weekend.",
    },
    "牵引绳套装": {
        "seo": "Italian Full-Grain Leather Dog Leash Set — Collar + Leash + Pouch, Solid Brass Hardware, Saddle-Stitched, Lifetime Warranty\n• Handcrafted from premium Italian full-grain leather that softens and ages beautifully — never peels, cracks, or flakes like cheap split-leather or PU sets\n• Double saddle-stitched seams and solid brass hardware rated to 200kg+ — built to hold even the strongest pullers on walks, training, or hikes\n• Complete matching set: collar + leash + convenient storage pouch in one box, so you save vs. buying each piece separately\n• Backed by a lifetime warranty — we replace it free if the leather or stitching ever fails, a promise 42 competing listings can't make\nWhat sets us apart: most $15–20 sets use split leather or PU that cracks within a year; ours is genuine full-grain leather with brass fittings that outlast your dog's pulling phase.\nTags: dog leash set, full grain leather leash, brass hardware dog collar, heavy duty leash, lifetime warranty leash, Italian leather dog collar, leash and collar set, no pull training leash",
        "social": "I went through three $15 leashes in two years before I finally stopped being cheap. Every single one cracked at the clip or the leather peeled into little flakes all over my car. Then I got this Italian leather set and honestly — it feels like a saddle, not a leash. The brass hardware is heavy and solid, and after six months of my 90lb lab lunging at every squirrel in the neighborhood, there's not a single crack. The matching collar and little storage pouch just make it feel like a proper gift to my dog. My only regret is not buying it the first time. 🐕",
        "sales": "Stop replacing a cracked leash every single year — 42 other listings are still selling split-leather and PU sets that peel within 12 months, and their reviews prove it. For just $22.99 you get a genuine Italian full-grain leather set with solid brass hardware, double saddle-stitching, a matching collar AND a storage pouch — the equivalent in a boutique pet store runs $60+. Over 4,000 verified buyers rate it 4.9 stars, and it's covered by a lifetime warranty, so it's the last leash you'll ever buy. That's under $23 for something your dog will pull against for a decade. ⚡ Add to cart now — our bestselling cognac and black are selling out this week.",
    },
    "换牙零食": {
        "seo": "100% Whole Chicken Breast Teething Treats for Puppies — Slow-Roasted 12 Hours, Individually Vacuum-Sealed, High Protein Low Fat\n• Made from 100% whole chicken breast — zero meat meal, zero starch, zero fillers, so picky eaters actually finish the bag\n• Slow-roasted at low temperature for 12 hours to lock in real flavor and a chewy texture that soothes sore teething gums\n• Individually vacuum-sealed for freshness — no stale, crumbly treats half-empty at the bottom of the bag\n• High protein, low fat formula supports healthy growth without the junk calories of starch-based competitors\n• Eat-it-or-money-back guarantee: if your dog won't eat them, we refund you in full — no questions asked\nWhat sets us apart: 30 competing treats load up on meat meal and starch that dogs sniff and walk away from; ours is single-ingredient real chicken with a repurchase rate of 8 bags a year per customer.\nTags: puppy teething treats, whole chicken breast dog treats, single ingredient dog treats, high protein low fat treats, slow roasted dog treats, picky eater dog treats, natural puppy chew treats, no filler dog treats",
        "social": "My puppy turned her nose up at THREE different teething treats before these. The vet said it's because cheap ones are mostly starch and meat meal — basically doggy cardboard. These are literally whole chicken breast slow-roasted for 12 hours, and you can smell the difference the second you open the pouch. She sits by the pantry and stares at the box now. The individual vacuum packs mean the last treat is as fresh as the first, which matters when your dog demolishes a bag a month. We're on our fourth bag and she hasn't refused a single one. Best $12 I've spent on her. 🦴",
        "sales": "Your puppy won't touch most teething treats — and here's why: 30 competing brands are still stuffing bags with meat meal and starch that dogs sniff once and ignore, then you throw the money away. Our treats are 100% whole chicken breast, slow-roasted for 12 hours, high protein and low fat, individually vacuum-sealed so every piece stays fresh. Loyal customers come back an average of 8 times a year — that's the proof. And we back it with a full eat-it-or-refund guarantee: your dog refuses them, you get every cent back. At $11.99 a bag, that's less than 40 cents a treat for something your puppy actually begs for. 🐾 Tap Add to Cart while this week's batch is still in stock.",
    },
    "宠物领结": {
        "seo": "Korean Pleated 3D Pet Bowtie — Velcro Attachment, No-Pull Comfort Fit, Detachable & Washable, 50+ Colors for Wedding, Photos & Holidays\n• Korean-style pleated 3D design holds its full, puffy shape all day — no more sad, flat bowties that droop mid-photo\n• Soft velcro attachment slides onto any collar and stays put without tightening or choking your pet — zero pressure, zero fuss\n• Detachable and machine-washable, so it survives mud, slobber, and birthdays and still looks new\n• 50+ colors and patterns: solids, plaid, polka dots, and limited holiday editions for every season and occasion\n• The go-to accessory for weddings, engagement photos, holiday cards, and daily walks that turn heads\nWhat sets us apart: 30 competing bowties come flat and thread a collar that rides up; our pleated 3D construction plus velcro keeps the look crisp and the fit gentle all day long.\nTags: pet bowtie, dog bowtie, cat bowtie, wedding dog bowtie, holiday pet bowtie, velcro dog bowtie, Korean style pet bowtie, photo prop dog bowtie, bowtie for collar",
        "social": "I needed ONE good photo of my dog for our wedding save-the-dates and this little bowtie is the reason they turned out perfect. The pleats are puffy and 3D so it actually looks like a real bowtie instead of a limp piece of fabric, and the velcro just wraps around his collar — no tugging, no choking, he didn't even notice it was on. He rolled in the grass, got it muddy, and it went straight in the wash and came out brand new. Now I buy a new pattern for every season — plaid for fall, red for Christmas cards. Best $10 I've ever spent on a photo prop. 🎀",
        "sales": "Your pet deserves better than a flat, droopy bowtie — and so do your photos. 30 other listings sell bowties that lay limp and thread onto collars that ride up and irritate your pet. Ours features a Korean pleated 3D design that stays perfectly puffy all day, with a soft velcro fit that never pulls or chokes, and it's fully washable for real life. With 50+ colors — solids, plaid, polka dots, and limited holiday editions — you'll grab one for the wedding, one for Christmas cards, and one for every walk. Wedding photographers charge a fortune, but this finishing touch is just $9.99. ✨ Get it before the holiday limited editions sell out again.",
    },
}
